"""In-process ``/升级bot`` state, convergence, and daemon conductor."""

from .conductor import (
    CandidateReadyPayload,
    Conductor,
    ConductorError,
    DeployOutcome,
    DeployResultPayload,
    E2ENotConvergingPayload,
    E2ERound,
    GitCommitReader,
    MainSyncFailure,
    MainSyncFailedPayload,
    RealUpgradeConductor,
    RenderedEvidence,
    SystemClock,
    ToolsDeployRunner,
    ToolsMainSync,
    UpgradeConductor,
    UpgradeEventSink,
)
from .convergence import (
    NON_CONVERGING_LIMIT,
    ConvergenceDecision,
    ConvergenceResult,
    RoundResult,
    RoundSummary,
    assess,
    evaluate,
    is_converging,
)
from .state import InvalidTransition, RunState, State, UpgradeState, allowed_transitions, transition

__all__ = [
    "CandidateReadyPayload",
    "Conductor",
    "ConductorError",
    "ConvergenceDecision",
    "ConvergenceResult",
    "DeployOutcome",
    "DeployResultPayload",
    "E2ENotConvergingPayload",
    "E2ERound",
    "GitCommitReader",
    "InvalidTransition",
    "MainSyncFailure",
    "MainSyncFailedPayload",
    "NON_CONVERGING_LIMIT",
    "RealUpgradeConductor",
    "RenderedEvidence",
    "RoundResult",
    "RoundSummary",
    "RunState",
    "State",
    "SystemClock",
    "ToolsDeployRunner",
    "ToolsMainSync",
    "UpgradeConductor",
    "UpgradeEventSink",
    "UpgradeState",
    "allowed_transitions",
    "assess",
    "evaluate",
    "is_converging",
    "transition",
]
